[package]
name = "schwab-api-sdk-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
async-oauth2 = "0.5.1"
reqwest = { version = "0.12.24", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = "1.48.0"
